### ISSUE TITLE
Generate TLS certificates

### ISSUE THREAD

**Issue by pgporada** [pgporada/wsu-base-site-docker#6]
Use smallstep, minica, or something else. Anything would be better than nothing. A wildcard would be best to cover `*.wayne.localhost`. Developers will need to accept the self-signed certificate though. During the `wild-wayne` days xip.io was used, but that service doesn't appear to exist anymore.

**Comment by chrispelzer** [comment]
With Wild Wayne, we would load the certificate that was generated with the box into the OSX Keychain

**Comment by pgporada** [comment]
That should still be fine for local development.

**Comment by pgporada** [comment]
Fixed by https://github.com/pgporada/wsu-base-site-docker/commit/e109a51106bd81e14249e7eb8b980bbc5730cf7d
